# Generated by Django 5.2.4 on 2025-07-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadImage',
            new_name='UploadedImage',
        ),
    ]
